// <auto-generated />
using System;
using FBQ.Salud_AccessData.Commands;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FBQ.Salud_AccessData.Migrations
{
    [DbContext(typeof(FbqSaludDbContext))]
    [Migration("20241207235426_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("HorarioId");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            EmpleadoId = 1,
                            Apellido = "Mcree",
                            Clave = "42205969Messi",
                            DNI = "201412521",
                            Estado = true,
                            Foto = "foto.jpg",
                            HorarioId = 1,
                            Nombre = "Mauricio",
                            TipoEmpleadoId = 1,
                            Usuario = "alamenda204"
                        },
                        new
                        {
                            EmpleadoId = 2,
                            Apellido = "Magno",
                            Clave = "42205969Messi",
                            DNI = "201412522",
                            Estado = true,
                            Foto = "foto.jpg",
                            HorarioId = 2,
                            Nombre = "Alejandro",
                            TipoEmpleadoId = 1,
                            Usuario = "alamenda209"
                        },
                        new
                        {
                            EmpleadoId = 3,
                            Apellido = "Tentaculos",
                            Clave = "42205969Messi",
                            DNI = "201412526",
                            Estado = true,
                            Foto = "foto.jpg",
                            HorarioId = 3,
                            Nombre = "Calamardo",
                            TipoEmpleadoId = 1,
                            Usuario = "Calamenda609"
                        },
                        new
                        {
                            EmpleadoId = 9,
                            Apellido = "Tentaculos",
                            Clave = "42205969essi",
                            DNI = "201412521",
                            Estado = true,
                            Foto = "foto.jpg",
                            HorarioId = 3,
                            Nombre = "Calamardo",
                            TipoEmpleadoId = 2,
                            Usuario = "Calamenda629"
                        },
                        new
                        {
                            EmpleadoId = 10,
                            Apellido = "Tentaculos",
                            Clave = "42205969Messi",
                            DNI = "201412526",
                            Estado = true,
                            Foto = "foto.jpg",
                            HorarioId = 3,
                            Nombre = "Calamardo",
                            TipoEmpleadoId = 2,
                            Usuario = "Calamenda609"
                        });
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Enfermera", b =>
                {
                    b.Property<int>("EnfermeraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnfermeraId"), 1L, 1);

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("HorarioId")
                        .HasColumnType("int");

                    b.Property<string>("TipoEnfermera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnfermeraId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Enfermeras");

                    b.HasData(
                        new
                        {
                            EnfermeraId = 1,
                            EmpleadoId = 1,
                            Estado = true,
                            HorarioId = 1,
                            TipoEnfermera = "MultiFuncion"
                        },
                        new
                        {
                            EnfermeraId = 2,
                            EmpleadoId = 2,
                            Estado = true,
                            HorarioId = 2,
                            TipoEnfermera = "Limpiador"
                        },
                        new
                        {
                            EnfermeraId = 3,
                            EmpleadoId = 3,
                            Estado = true,
                            HorarioId = 3,
                            TipoEnfermera = "MultiFuncion"
                        });
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Especialidad", b =>
                {
                    b.Property<int>("EspecialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspecialidadId");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            EspecialidadId = 1,
                            Descripcion = "pediatra"
                        },
                        new
                        {
                            EspecialidadId = 2,
                            Descripcion = "cabecera"
                        });
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Habitacion", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HabitacionId"), 1L, 1);

                    b.Property<int>("EnfermeraId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.HasKey("HabitacionId");

                    b.HasIndex("EnfermeraId");

                    b.ToTable("Habitaciones");

                    b.HasData(
                        new
                        {
                            HabitacionId = 1,
                            EnfermeraId = 1,
                            Estado = true,
                            Fecha = new DateTime(2024, 12, 7, 20, 54, 26, 556, DateTimeKind.Local).AddTicks(3052),
                            Numero = 204,
                            PacienteId = 1,
                            Piso = 1
                        },
                        new
                        {
                            HabitacionId = 2,
                            EnfermeraId = 1,
                            Estado = true,
                            Fecha = new DateTime(2024, 12, 7, 20, 54, 26, 556, DateTimeKind.Local).AddTicks(3062),
                            Numero = 205,
                            PacienteId = 2,
                            Piso = 1
                        },
                        new
                        {
                            HabitacionId = 3,
                            EnfermeraId = 1,
                            Estado = true,
                            Fecha = new DateTime(2024, 12, 7, 20, 54, 26, 556, DateTimeKind.Local).AddTicks(3063),
                            Numero = 206,
                            PacienteId = 3,
                            Piso = 1
                        },
                        new
                        {
                            HabitacionId = 4,
                            EnfermeraId = 1,
                            Estado = true,
                            Fecha = new DateTime(2024, 12, 7, 20, 54, 26, 556, DateTimeKind.Local).AddTicks(3064),
                            Numero = 207,
                            PacienteId = 4,
                            Piso = 1
                        },
                        new
                        {
                            HabitacionId = 5,
                            EnfermeraId = 2,
                            Estado = true,
                            Fecha = new DateTime(2024, 12, 7, 20, 54, 26, 556, DateTimeKind.Local).AddTicks(3065),
                            Numero = 208,
                            PacienteId = 5,
                            Piso = 1
                        },
                        new
                        {
                            HabitacionId = 6,
                            EnfermeraId = 2,
                            Estado = true,
                            Fecha = new DateTime(2024, 12, 7, 20, 54, 26, 556, DateTimeKind.Local).AddTicks(3066),
                            Numero = 209,
                            PacienteId = 6,
                            Piso = 1
                        },
                        new
                        {
                            HabitacionId = 7,
                            EnfermeraId = 3,
                            Estado = true,
                            Fecha = new DateTime(2024, 12, 7, 20, 54, 26, 556, DateTimeKind.Local).AddTicks(3067),
                            Numero = 210,
                            PacienteId = 7,
                            Piso = 1
                        },
                        new
                        {
                            HabitacionId = 8,
                            EnfermeraId = 3,
                            Estado = true,
                            Fecha = new DateTime(2024, 12, 7, 20, 54, 26, 556, DateTimeKind.Local).AddTicks(3068),
                            Numero = 211,
                            PacienteId = 8,
                            Piso = 1
                        });
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.HorarioTrabajo", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorarioId"), 1L, 1);

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HorarioId");

                    b.ToTable("HorariosTrabajo");

                    b.HasData(
                        new
                        {
                            HorarioId = 1,
                            DiaSemana = "Lunes",
                            Estado = true,
                            Fecha = "24/10/22",
                            HoraFin = "18:00",
                            HoraInicio = "07:00"
                        },
                        new
                        {
                            HorarioId = 2,
                            DiaSemana = "Lunes",
                            Estado = true,
                            Fecha = "24/10/22",
                            HoraFin = "07:00",
                            HoraInicio = "18:00"
                        },
                        new
                        {
                            HorarioId = 3,
                            DiaSemana = "Martes",
                            Estado = true,
                            Fecha = "25/10/22",
                            HoraFin = "18:00",
                            HoraInicio = "07:00"
                        });
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Medico", b =>
                {
                    b.Property<int>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicoId"), 1L, 1);

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("HorarioId")
                        .HasColumnType("int");

                    b.HasKey("MedicoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            EmpleadoId = 9,
                            EspecialidadId = 1,
                            Estado = true,
                            HorarioId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            EmpleadoId = 10,
                            EspecialidadId = 2,
                            Estado = true,
                            HorarioId = 1
                        });
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.TipoEmpleado", b =>
                {
                    b.Property<int>("TipoEmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoEmpleadoId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("TipoEmpleadoId");

                    b.ToTable("TipoEmpleados");

                    b.HasData(
                        new
                        {
                            TipoEmpleadoId = 1,
                            Descripcion = "Enfermera",
                            Estado = true
                        },
                        new
                        {
                            TipoEmpleadoId = 2,
                            Descripcion = "Medico",
                            Estado = true
                        });
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Empleado", b =>
                {
                    b.HasOne("FBQ.Salud_Domain.Entities.HorarioTrabajo", "horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("horario");
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Enfermera", b =>
                {
                    b.HasOne("FBQ.Salud_Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Habitacion", b =>
                {
                    b.HasOne("FBQ.Salud_Domain.Entities.Enfermera", "Enfermera")
                        .WithMany()
                        .HasForeignKey("EnfermeraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfermera");
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Medico", b =>
                {
                    b.HasOne("FBQ.Salud_Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FBQ.Salud_Domain.Entities.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Especialidad");
                });
#pragma warning restore 612, 618
        }
    }
}
